name: Valist Publish
on:
  push:
    branches:
      - master
jobs:
  valist-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build and export Next.js app
        run: |
          npm install
          npm run build

      - run: echo "TIMESTAMP=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Valist Publish
        uses: darcksday/challenge
        with:
          private-key: ${{ secrets.VALIST_SIGNER }}
          account: darcksday
          project: chalange
          release: github-action-${{ env.TIMESTAMP }}
          path: dist
